# -*- coding: utf-8 -*-
"""AE461.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X121yzPsVcldMxDB_v0sSYK_TlSOgCKX
"""

import numpy as np
import matplotlib.pyplot as plt

W = 1465.5  #Mid cruise weight
Cd0 = 0.028
k = 0.04
s = 12.2
v = np.linspace(30,90,7) #Velocity from 30 to 90m/s at step of 10m/s
h = np.linspace(0,10,11) #Altitude fromm sea level to 10 km
rho = np.array([1.225, 1.112, 1.007, 0.9093, 0.8194, 0.7364, 0.6601, 0.5900, 0.5258, 0.4671, 0.4135]) #Rho from sea level to 10 km
P_cruise = np.zeros((rho.shape[0],v.shape[0]))
roc = np.linspace(2,10,5) # given RoC

for i in range(11):
  for n in range(7):
    P_cruise[i,n] = 0.5*s*Cd0*rho[i]*((v[n])**3) + 2*k*(W**2)*(9.8**2)/(rho[i]*s*v[n])
  plt.plot(v,P_cruise[i]/745.69, label='h = %d km' %(h[i]), marker='o') 
plt.rcParams['figure.figsize'] = [10, 10]  
plt.ylabel('Aerodynamic Power (hp)') 
plt.xlabel('V (m/s)')  
plt.title('Drag Power at cruise vs v') 
plt.grid() 
plt.legend(loc=(1.04,0)) 
plt.show()

for i in range(5):
   plt.plot(v,(P_cruise[4-i]+ W*9.8*roc[i])/745.69, label='h= %dkm---roc= %dm/s' %(h[4-i],roc[i]), marker='o')
plt.rcParams['figure.figsize'] = [10, 10]  
plt.ylabel('Power Required from Engine (hp)') 
plt.xlabel('V (m/s)')  
plt.title('Power required from engine at climb vs v') 
plt.grid() 
plt.legend(loc=(1.04,0)) 
plt.show()
print((P_cruise[3,3]+ W*9.8*3)/745.69)